// <auto-generated />
using System;
using LasteaedERD_SergeiBubnov_TARpe20.CFM.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LasteaedERD_SergeiBubnov_TARpe20.CFM.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20210915144532_Kinergarten")]
    partial class Kinergarten
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ChildGroup", b =>
                {
                    b.Property<int>("ChildrenChildId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("ChildrenChildId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("ChildGroup");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Absence", b =>
                {
                    b.Property<int>("AbsenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateofAbsence")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AbsenceId");

                    b.ToTable("Absence");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Child", b =>
                {
                    b.Property<int>("ChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ListOfEnteringLOEId")
                        .HasColumnType("int");

                    b.HasKey("ChildId");

                    b.HasIndex("ListOfEnteringLOEId");

                    b.ToTable("Child");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Cook", b =>
                {
                    b.Property<int>("CookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KitchenId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("CookId");

                    b.HasIndex("KitchenId");

                    b.ToTable("Cook");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.EatingHistory", b =>
                {
                    b.Property<int>("EHId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DayOfEating")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnergyValue")
                        .HasColumnType("int");

                    b.Property<int>("Portion")
                        .HasColumnType("int");

                    b.HasKey("EHId");

                    b.ToTable("EatingHistory");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ChildrenIds")
                        .HasColumnType("int");

                    b.Property<string>("GroupType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ListOfEnteringLOEId")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.HasIndex("ListOfEnteringLOEId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.GroupHistory", b =>
                {
                    b.Property<int>("GroupHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("BeginningDay")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChildId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDay")
                        .HasColumnType("datetime2");

                    b.HasKey("GroupHistoryId");

                    b.HasIndex("ChildId");

                    b.ToTable("GroupHistory");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Kitchen", b =>
                {
                    b.Property<int>("KitchenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CookId")
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.HasKey("KitchenId");

                    b.ToTable("Kitchen");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.ListOfEntering", b =>
                {
                    b.Property<int>("LOEId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<int>("PositionInList")
                        .HasColumnType("int");

                    b.Property<int>("wantedGroupId")
                        .HasColumnType("int");

                    b.HasKey("LOEId");

                    b.ToTable("ListOfEntering");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DatesofMenu")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dishes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnergyValue")
                        .HasColumnType("int");

                    b.Property<int?>("KitchenId")
                        .HasColumnType("int");

                    b.HasKey("MenuId");

                    b.HasIndex("KitchenId");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CookId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkingHistoryWHId")
                        .HasColumnType("int");

                    b.Property<string>("positionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PositionId");

                    b.HasIndex("CookId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("WorkingHistoryWHId");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("WHId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.WorkingHistory", b =>
                {
                    b.Property<int>("WHId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("BeginningDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDay")
                        .HasColumnType("datetime2");

                    b.Property<int>("PositionIds")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("WHId");

                    b.HasIndex("TeacherId");

                    b.ToTable("WorkiHistory");
                });

            modelBuilder.Entity("ChildGroup", b =>
                {
                    b.HasOne("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Child", null)
                        .WithMany()
                        .HasForeignKey("ChildrenChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Child", b =>
                {
                    b.HasOne("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.ListOfEntering", null)
                        .WithMany("Child")
                        .HasForeignKey("ListOfEnteringLOEId");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Cook", b =>
                {
                    b.HasOne("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Kitchen", null)
                        .WithMany("Cook")
                        .HasForeignKey("KitchenId");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Group", b =>
                {
                    b.HasOne("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.ListOfEntering", null)
                        .WithMany("wantedGroup")
                        .HasForeignKey("ListOfEnteringLOEId");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.GroupHistory", b =>
                {
                    b.HasOne("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Child", null)
                        .WithMany("groupHistory")
                        .HasForeignKey("ChildId");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Menu", b =>
                {
                    b.HasOne("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Kitchen", null)
                        .WithMany("MenuOfTheWeek")
                        .HasForeignKey("KitchenId");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Position", b =>
                {
                    b.HasOne("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Cook", null)
                        .WithMany("position")
                        .HasForeignKey("CookId");

                    b.HasOne("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Teacher", null)
                        .WithMany("Position")
                        .HasForeignKey("TeacherId");

                    b.HasOne("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.WorkingHistory", null)
                        .WithMany("Positions")
                        .HasForeignKey("WorkingHistoryWHId");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.WorkingHistory", b =>
                {
                    b.HasOne("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Teacher", null)
                        .WithMany("WH")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Child", b =>
                {
                    b.Navigation("groupHistory");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Cook", b =>
                {
                    b.Navigation("position");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Kitchen", b =>
                {
                    b.Navigation("Cook");

                    b.Navigation("MenuOfTheWeek");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.ListOfEntering", b =>
                {
                    b.Navigation("Child");

                    b.Navigation("wantedGroup");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.Teacher", b =>
                {
                    b.Navigation("Position");

                    b.Navigation("WH");
                });

            modelBuilder.Entity("LasteaedERD_SergeiBubnov_TARpe20.CFM.Models.WorkingHistory", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
